import { useState, useEffect, useRef } from 'react';
import { Send, Bot, Shield, Zap, CheckCircle, Settings, HelpCircle } from 'lucide-react';
import { useClient } from '../../context/ClientContext'; // Import Context

interface Message {
    id: string;
    sender: 'bot' | 'user';
    text: string;
    isQuestion?: boolean;
    fieldToUpdate?: 'avgHourlyRate' | 'employeeCount'; // Metadata for what this question answers
}

// Comprehensive Question Bank
const AUDIT_QUESTIONS = [
    // SHIELD TRACK (Security & Governance)
    {
        id: 'shield_1',
        track: 'shield',
        text: "Let's talk Security. be precise: How many employees interpret 'Do not put PII in ChatGPT' as 'It's fine if I remove the names'?",
        type: 'sentiment',
        riskKeywords: ['many', 'most', 'all', 'lot', 'yes', 'everyone'],
        frictionImpact: 15, // High impact on risk score
        followUp: "That's a common data leak vector. It implies your DLP policy is failing at the 'human firewall' layer."
    },
    {
        id: 'shield_2',
        track: 'shield',
        text: "Who specifically receives the alert when an AI agent hallucinates or goes rogue? (If the answer is 'no one' or 'the intern', be honest).",
        type: 'binary',
        riskKeywords: ['no one', 'nobody', 'intern', 'don\'t know', 'none'],
        frictionImpact: 20,
        followUp: "Orchestration without observation is just automated chaos."
    },
    // SPEAR TRACK (Culture & ROI)
    {
        id: 'spear_1',
        track: 'spear',
        text: "Switching to Culture. When you introduce a new AI tool, what is the dominant emotion in the Slack channels? Fear (replacement) or Fatigue (another login)?",
        type: 'sentiment',
        riskKeywords: ['fear', 'scared', 'replacement', 'worry', 'jobs'],
        frictionImpact: 10, // Impact on culture score
        followUp: "Fear freezes adoption. You can't deploy 'Spear' strategies if the troops are afraid of the weapon."
    },
    {
        id: 'spear_2',
        track: 'spear',
        text: "Real talk on ROI: Can you point to a *single* dollar of new revenue generated by AI this month, or is it all just 'time saved'?",
        type: 'binary',
        riskKeywords: ['no', 'time saved', 'efficiency', 'cost', 'saving'],
        frictionImpact: 10,
        followUp: "Efficiency is a trap. Growth (Revenue) is the only metric that survives the next budget cut."
    }
];

export function AuditScout() {
    const {
        identifiedRisks, frictionCost, costBasis, updateCostBasis,
        shieldScore, spearScore, updateScores, isOnboarding
    } = useClient();

    const [messages, setMessages] = useState<Message[]>([]);
    const [inputText, setInputText] = useState('');
    const [step, setStep] = useState<'calibration' | 'audit' | 'complete'>('calibration');
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [isTyping, setIsTyping] = useState(false);
    const scrollRef = useRef<HTMLDivElement>(null);

    // Initial Boot
    useEffect(() => {
        if (identifiedRisks.length > 0 && messages.length === 0) {
            setMessages([
                {
                    id: 'init',
                    sender: 'bot',
                    text: `I see ${identifiedRisks.length} potential risks in your stack. To calculate the REAL COST of this friction, I need to check my assumptions.`,
                },
                {
                    id: 'q1',
                    sender: 'bot',
                    text: `I'm assuming an average IT hourly rate of $${costBasis.avgHourlyRate}. Is that accurate? If not, type the correct rate (e.g., '90').`,
                    isQuestion: true,
                    fieldToUpdate: 'avgHourlyRate'
                }
            ]);
        } else if (messages.length === 0) {
            setMessages([{
                id: 'empty',
                sender: 'bot',
                text: isOnboarding
                    ? "Welcome to the Sandbox. Your simulated stack looks clean. Add some potentially risky tools in the Stack Map to see me in action!"
                    : "Awaiting live meeting sync for audit context... Connect the Maestro MeetingParser to begin real-time risk orchestration."
            }]);
        }
    }, [identifiedRisks.length, isOnboarding]); // Only run once or when risks change significantly

    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, isTyping]);

    const handleSend = async () => {
        if (!inputText.trim()) return;

        // User message
        const userMsg: Message = { id: Date.now().toString(), sender: 'user', text: inputText };
        setMessages(prev => [...prev, userMsg]);
        setInputText('');
        setIsTyping(true);

        // LOGIC: Process Answer
        const lastBotQuestion = messages.slice().reverse().find(m => m.sender === 'bot');

        // Simulate Processing
        setTimeout(() => {
            let responseText = "";
            let nextQuestionMsg: Message | null = null;

            // --- PHASE 1: CALIBRATION ---
            if (step === 'calibration') {
                if (lastBotQuestion?.fieldToUpdate === 'avgHourlyRate') {
                    const rate = parseInt(inputText.replace(/[^0-9]/g, ''));
                    if (!isNaN(rate)) {
                        updateCostBasis({ avgHourlyRate: rate });
                        responseText = `Updated. Using $${rate}/hr.`;
                    } else {
                        responseText = `Keeping rate at $${costBasis.avgHourlyRate}/hr.`;
                    }

                    nextQuestionMsg = {
                        id: 'q2',
                        sender: 'bot',
                        text: `And for the team size affected by these tools... I have ${costBasis.employeeCount} employees. Roughly correct?`,
                        isQuestion: true,
                        fieldToUpdate: 'employeeCount'
                    };
                }
                else if (lastBotQuestion?.fieldToUpdate === 'employeeCount') {
                    const count = parseInt(inputText.replace(/[^0-9]/g, ''));
                    if (!isNaN(count)) {
                        updateCostBasis({ employeeCount: count });
                        responseText = `Got it. ${count} employees.`;
                    } else {
                        responseText = `Keeping size at ${costBasis.employeeCount}.`;
                    }
                    setStep('audit'); // Transition

                    // Start Question 1
                    const firstQ = AUDIT_QUESTIONS[0];
                    nextQuestionMsg = {
                        id: firstQ.id,
                        sender: 'bot',
                        text: `Calibration complete. Now, let's look at the **${firstQ.track.toUpperCase()}** track.\n\n${firstQ.text}`,
                        isQuestion: true
                    };
                    setCurrentQuestionIndex(0);
                }
            }

            // --- PHASE 2: AUDIT QUESTIONS ---
            else if (step === 'audit') {
                const currentQ = AUDIT_QUESTIONS[currentQuestionIndex];

                // Analyze Sentiment / Keywords
                const lowerInput = inputText.toLowerCase();
                const isRisky = currentQ.riskKeywords.some(w => lowerInput.includes(w));

                // Update Context Scores
                if (isRisky) {
                    if (currentQ.track === 'shield') updateScores(-currentQ.frictionImpact, 0); // Drop Shield
                    if (currentQ.track === 'spear') updateScores(0, -currentQ.frictionImpact); // Drop Spear
                } else {
                    // Slight bonus for good answers
                    if (currentQ.track === 'shield') updateScores(5, 0);
                    if (currentQ.track === 'spear') updateScores(0, 5);
                }

                responseText = isRisky ? `🚩 **Risk Detected.** ${currentQ.followUp}` : `✅ **Good.** ${currentQ.followUp}`;

                // Queue Next Question
                const nextIdx = currentQuestionIndex + 1;
                if (nextIdx < AUDIT_QUESTIONS.length) {
                    const nextQ = AUDIT_QUESTIONS[nextIdx];
                    nextQuestionMsg = {
                        id: nextQ.id,
                        sender: 'bot',
                        text: nextQ.text,
                        isQuestion: true
                    };
                    setCurrentQuestionIndex(nextIdx);
                } else {
                    setStep('complete');
                    nextQuestionMsg = {
                        id: 'complete',
                        sender: 'bot',
                        text: "Audit complete. I've updated your Shield & Spear scores. You should proceed to the **Maturity Assessment** for a deep-dive, or generate your 'Mess Map' report now.",
                        isQuestion: false
                    };
                }
            }

            const newMsgs = [{ id: `resp-${Date.now()}`, sender: 'bot', text: responseText, isQuestion: false } as Message];
            if (nextQuestionMsg) newMsgs.push(nextQuestionMsg);

            setMessages(prev => [...prev, ...newMsgs]);
            setIsTyping(false);
        }, 1500);
    };

    return (
        <div className="flex h-full bg-zinc-50 dark:bg-zinc-950 p-8 gap-8">
            {/* Chat Area */}
            <div className="flex-1 flex flex-col max-w-3xl mx-auto bg-card border border-border rounded-xl shadow-lg overflow-hidden">
                <div className="p-4 border-b border-border bg-muted/30 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500 border border-amber-500/20">
                            <Bot className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-orange-400">The Audit Scout</h3>
                            <p className="text-xs text-zinc-400">Orchestration Integrity Check</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        {step === 'calibration' && (
                            <div className="text-xs font-bold text-amber-500 animate-pulse flex items-center gap-1">
                                <Settings className="w-3 h-3" /> Calibrating Cost Basis...
                            </div>
                        )}
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-4 space-y-6" ref={scrollRef}>
                    {messages.map(msg => (
                        <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                            <div className={`max-w-[80%] rounded-2xl px-5 py-3 ${msg.sender === 'user'
                                ? 'bg-primary text-primary-foreground rounded-tr-none font-medium'
                                : 'bg-zinc-800 text-zinc-100 border border-zinc-700 rounded-tl-none shadow-sm'
                                }`}>
                                <p className="text-sm leading-relaxed whitespace-pre-wrap">{msg.text}</p>
                            </div>
                        </div>
                    ))}
                    {isTyping && (
                        <div className="flex justify-start">
                            <div className="bg-secondary text-secondary-foreground rounded-2xl rounded-tl-none px-4 py-3 flex gap-1">
                                <span className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce" />
                                <span className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce delay-75" />
                                <span className="w-2 h-2 bg-muted-foreground/40 rounded-full animate-bounce delay-150" />
                            </div>
                        </div>
                    )}
                </div>

                <div className="p-4 border-t border-border bg-muted/10">
                    <form
                        onSubmit={(e) => { e.preventDefault(); handleSend(); }}
                        className="flex items-center gap-2"
                    >
                        <input
                            autoFocus
                            value={inputText}
                            onChange={e => setInputText(e.target.value)}
                            placeholder={step === 'calibration' ? "Enter a number..." : "Type your answer... be honest."}
                            className="flex-1 bg-zinc-900 border border-zinc-700 rounded-full px-4 py-3 text-sm text-white focus:ring-2 focus:ring-primary outline-none placeholder:text-zinc-600"
                        />
                        <button
                            type="submit"
                            disabled={!inputText.trim() || isTyping}
                            className="p-3 bg-primary text-primary-foreground rounded-full hover:bg-primary/90 disabled:opacity-50 transition-all border border-white/10"
                        >
                            <Send className="w-4 h-4 ml-0.5" />
                        </button>
                        {step === 'complete' && (
                            <button
                                onClick={() => window.dispatchEvent(new CustomEvent('navigate', { detail: 'roadmap' }))}
                                className="w-full mt-6 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-bold flex items-center justify-center gap-2 animate-pulse hover:scale-105 transition-transform"
                            >
                                <CheckCircle className="w-4 h-4" /> View Remediation Plan
                            </button>
                        )}        </form>
                </div>
            </div>

            {/* Live "Shield & Spear" Analysis */}
            <div className="w-full lg:w-80 space-y-6 shrink-0">

                {/* Cost Analysis Card */}
                <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
                    <h4 className="font-bold text-sm mb-4 flex items-center justify-between text-zinc-100">
                        <span className="flex items-center gap-2"><HelpCircle className="w-4 h-4 text-primary" /> Cost Analysis</span>
                    </h4>

                    {/* The "Proven" Formula */}
                    <div className="space-y-3 text-xs">
                        <div className="p-3 bg-zinc-900/50 rounded-lg space-y-2 border border-zinc-800">
                            <div className="flex justify-between items-center text-zinc-400">
                                <span>Risks Found:</span>
                                <span className="font-mono font-bold text-zinc-100">{identifiedRisks.length}</span>
                            </div>
                            <div className="flex justify-between items-center text-zinc-400">
                                <span>Avg. Hourly Rate:</span>
                                <span className="font-mono font-bold text-zinc-100">${costBasis.avgHourlyRate}</span>
                            </div>
                            <div className="flex justify-between items-center text-zinc-400">
                                <span>Fix Time (Hrs):</span>
                                <span className="font-mono font-bold text-zinc-100">{costBasis.remediationTimePerIncident}h</span>
                            </div>
                            <div className="border-t border-zinc-800 my-2" />
                            <div className="flex justify-between items-center text-zinc-400">
                                <span>Incidents / Month:</span>
                                <span className="font-mono font-bold text-zinc-100">{costBasis.incidentsPerMonth}</span>
                            </div>
                        </div>

                        <div className="pt-2">
                            <div className="flex justify-between items-end">
                                <span className="font-bold text-zinc-400">Total Friction:</span>
                                <span className="font-mono font-bold text-red-400 text-xl">${frictionCost.toLocaleString()}/mo</span>
                            </div>
                            <p className="text-[10px] mt-2 text-zinc-500 border-l-2 border-red-500/20 pl-2">
                                <b>Formula:</b> {identifiedRisks.length} Risks × {costBasis.incidentsPerMonth} Incidents × ({costBasis.remediationTimePerIncident}h × ${costBasis.avgHourlyRate}/hr)
                            </p>
                        </div>
                    </div>
                </div>

                {/* Shield Card (Security) */}
                <div className={`bg-card border rounded-xl p-6 transition-all duration-500 ${shieldScore < 80 ? "border-red-500/50 shadow-lg shadow-red-500/10" : "border-border"}`}>
                    <h4 className="font-bold text-sm mb-4 flex items-center justify-between">
                        <span className="flex items-center gap-2"><Shield className={`w-4 h-4 ${shieldScore < 80 ? "text-red-500" : "text-emerald-500"}`} /> Shield Score</span>
                        <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded ${shieldScore < 80 ? "bg-red-500/20 text-red-500" : "bg-emerald-500/20 text-emerald-500"}`}>
                            {shieldScore}%
                        </span>
                    </h4>
                    <div className="w-full bg-secondary h-2 rounded-full overflow-hidden">
                        <div className={`h-full ${shieldScore < 80 ? "bg-red-500" : "bg-emerald-500"} transition-all duration-1000`} style={{ width: `${shieldScore}%` }} />
                    </div>
                </div>

                {/* Spear Card (Culture) */}
                <div className={`bg-card border rounded-xl p-6 transition-all duration-500 ${spearScore < 50 ? "border-amber-500/50" : "border-border"}`}>
                    <h4 className="font-bold text-sm mb-4 flex items-center justify-between">
                        <span className="flex items-center gap-2"><Zap className={`w-4 h-4 ${spearScore < 50 ? "text-amber-500" : "text-blue-500"}`} /> Spear Score</span>
                        <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded ${spearScore < 50 ? "bg-amber-500/20 text-amber-500" : "bg-blue-500/20 text-blue-500"}`}>
                            {spearScore}%
                        </span>
                    </h4>
                    <div className="w-full bg-secondary h-2 rounded-full overflow-hidden">
                        <div className={`h-full ${spearScore < 50 ? "bg-amber-500" : "bg-blue-500"} transition-all duration-1000`} style={{ width: `${spearScore}%` }} />
                    </div>
                </div>

            </div>
        </div>
    );
}
