import { useState } from 'react';
import { ShieldCheck, Lock, Activity, Eye, FileCheck, X, AlertTriangle, CheckCircle, Info, Cpu, Database } from 'lucide-react';
import { cn } from '../lib/utils';
import { useClient } from '../context/ClientContext';

export function GovernanceHUD() {
    const { shieldScore } = useClient();
    const [selectedLayer, setSelectedLayer] = useState<any>(null);

    const layers = [
        {
            id: 'l7',
            name: "Layer 7: Ecosystem",
            status: "Active",
            icon: Activity,
            color: "text-green-500",
            title: "Ecosystem Integrity",
            description: "Ensures that the external tools (SaaS) connected to your architecture are not compromised.",
            whyItMatters: "If Salesforce or Slack is breached, your internal agents could inadvertently leak data. We constantly monitor API health and vendor security advisories.",
            maestroCheck: "Real-time API Heartbeat & Vendor Risk Scoring."
        },
        {
            id: 'l6',
            name: "Layer 6: Auth/Identity",
            status: "Verified",
            icon: Lock,
            color: "text-blue-500",
            title: "Identity & Access (IAM)",
            description: "Verifies exactly WHO (human) or WHAT (agent) is requesting action.",
            whyItMatters: "Agents need identities too. You don't want the 'Writer Agent' to have permission to delete the production database. We enforce strict Least Privilege.",
            maestroCheck: "Role-Based Access Control (RBAC) for every Agent Interaction."
        },
        {
            id: 'l5',
            name: "Layer 5: Compliance",
            status: "ISO 42001",
            icon: FileCheck,
            color: "text-emerald-500",
            title: "Regulatory Compliance",
            description: "Maps every AI action to legal frameworks (GDPR, ISO 42001, EU AI Act).",
            whyItMatters: "Ignorance is not a defense. If an agent processes PII illegally, you are liable. This layer blocks actions that violate your specific compliance profile.",
            maestroCheck: "Automated PII Redaction & Audit Logging."
        },
        {
            id: 'l4',
            name: "Layer 4: Sandbox",
            status: "Isolated",
            icon: ShieldCheck,
            color: "text-purple-500",
            title: "Execution Sandboxing",
            description: "Code generated by AI is run in a disposable, isolated container—never on your main server.",
            whyItMatters: "AI writes buggy code. Without a sandbox, a 'simple script' could wipe your laptop or expose environment variables.",
            maestroCheck: "Ephemeral Docker Containers for all Code Execution."
        },
        {
            id: 'l3',
            name: "Layer 3: Agent Logic",
            status: "Monitoring",
            icon: Eye,
            color: "text-amber-500",
            title: "Cognitive Monitoring",
            description: "Watches the 'thought process' of the agent for loops, hallucinations, or drift.",
            whyItMatters: "Agents can get stuck or confidentially wrong. We analyze the chain-of-thought before the final action is taken.",
            maestroCheck: "Hallucination Detection & Sentiment Analysis."
        },
        {
            id: 'l2',
            name: "Layer 2: Model Grid",
            status: "Optimized",
            icon: Database,
            color: "text-orange-500",
            title: "Inference & Model Safety",
            description: "Manages the specific LLM being used (GPT-4, Claude, Llama 3) and switches based on cost/risk profile.",
            whyItMatters: "Using GPT-4 for simple classification is a waste of money. Using Llama 7B for medical advice is a liability. We route prompts to the 'Right Model for the Right Job'.",
            maestroCheck: "Dynamic Model Routing & Context Window Management."
        },
        {
            id: 'l1',
            name: "Layer 1: Compute",
            status: "Secure",
            icon: Cpu,
            color: "text-red-500",
            title: "Physical Infrastructure",
            description: "The metallic reality. Where is the GPU? Which region is the data stored in? Is it sovereign?",
            whyItMatters: "Data Sovereignty. If your government requires data to stay in the EU, you cannot use a US-based inference cluster. We pin compute to specific geographies.",
            maestroCheck: "Region-Locking & Private VPC Deployment."
        },
    ];

    return (
        <div className="p-4 h-full flex flex-col font-mono relative">
            <h2 className="text-xs font-bold uppercase tracking-widest text-zinc-500 mb-6 border-b border-border pb-2 flex justify-between items-center">
                <span>Security Stack</span>
                <span className="bg-emerald-500/10 text-emerald-500 px-1.5 py-0.5 rounded text-[10px]">v2.1</span>
            </h2>

            <div className="space-y-3">
                {layers.map((layer) => (
                    <button
                        key={layer.name}
                        onClick={() => setSelectedLayer(layer)}
                        className="w-full flex items-center justify-between p-3 bg-secondary/30 hover:bg-secondary/60 hover:border-primary/30 rounded-lg border border-border/50 transition-all text-left group"
                    >
                        <div className="flex items-center gap-3">
                            <layer.icon className={cn("w-5 h-5 transition-transform group-hover:scale-110", layer.color)} />
                            <div className="flex flex-col">
                                <span className="text-xs font-semibold text-foreground group-hover:text-primary transition-colors">{layer.name}</span>
                                <span className="text-[10px] text-muted-foreground uppercase">{layer.status}</span>
                            </div>
                        </div>
                        <div className="flex items-center gap-2">
                            <Info className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
                            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse shadow-[0_0_8px_rgba(16,185,129,0.4)]" />
                        </div>
                    </button>
                ))}
            </div>

            <div className="mt-auto p-4 rounded-lg bg-emerald-500/5 border border-emerald-500/20 text-emerald-600 dark:text-emerald-400">
                <div className="flex items-center gap-2 mb-2">
                    <ShieldCheck className="w-5 h-5" />
                    <span className="font-bold text-sm">System Secure</span>
                </div>
                <p className="text-xs opacity-90 leading-relaxed">
                    Maestro Framework is enforcing <span className="font-bold">{shieldScore}%</span> governance score. All layers active.
                </p>
            </div>

            {/* Educational Modal */}
            {selectedLayer && (
                <div className="absolute inset-0 z-50 bg-background/95 backdrop-blur-sm p-4 flex flex-col animate-in slide-in-from-right-10 duration-200">
                    <button
                        onClick={() => setSelectedLayer(null)}
                        className="absolute top-4 right-4 p-1 hover:bg-secondary rounded-full"
                    >
                        <X className="w-5 h-5" />
                    </button>

                    <div className="mt-8 flex flex-col h-full overflow-y-auto pr-2">
                        <div className={cn("w-12 h-12 rounded-xl flex items-center justify-center mb-4 bg-opacity-10", selectedLayer.color.replace('text-', 'bg-'))}>
                            <selectedLayer.icon className={cn("w-6 h-6", selectedLayer.color)} />
                        </div>

                        <h3 className="text-lg font-bold mb-1 mr-8">{selectedLayer.title}</h3>
                        <p className="text-xs font-mono text-muted-foreground mb-6 uppercase tracking-wider">{selectedLayer.name}</p>

                        <div className="space-y-6">
                            <div className="bg-card border border-border rounded-lg p-4">
                                <h4 className="text-sm font-bold flex items-center gap-2 mb-2 text-primary">
                                    <Info className="w-4 h-4" /> What is this?
                                </h4>
                                <p className="text-sm text-muted-foreground leading-relaxed">{selectedLayer.description}</p>
                            </div>

                            <div>
                                <h4 className="text-sm font-bold flex items-center gap-2 mb-2 text-amber-500">
                                    <AlertTriangle className="w-4 h-4" /> Why it Matters
                                </h4>
                                <p className="text-sm text-foreground leading-relaxed pl-6 border-l-2 border-amber-500/20">
                                    "{selectedLayer.whyItMatters}"
                                </p>
                            </div>

                            <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-lg p-4">
                                <h4 className="text-sm font-bold flex items-center gap-2 mb-2 text-emerald-600 dark:text-emerald-400">
                                    <CheckCircle className="w-4 h-4" /> Maestro Protection
                                </h4>
                                <p className="text-sm opacity-90 font-medium">{selectedLayer.maestroCheck}</p>
                            </div>
                        </div>

                        <div className="mt-auto pt-6 text-center">
                            <p className="text-[10px] text-muted-foreground uppercase tracking-widest">Maestro Architecture v1.0</p>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

