
import React, { useState } from 'react';
import { useClient } from '../../context/ClientContext';
import { PenTool, Linkedin, FileText, Mic, Copy, RefreshCw, Check, Sparkles } from 'lucide-react';

type ContentType = 'linkedin' | 'blog' | 'email';

export function ContentStudio() {
    const { companyName, frictionCost, identifiedRisks, costBasis, shieldScore } = useClient();
    const [activeTab, setActiveTab] = useState<ContentType>('linkedin');
    const [generatedContent, setContent] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    // "Writer Agent" Logic (Simulated)
    const generateContent = (type: ContentType) => {
        setIsGenerating(true);
        setContent(''); // Clear previous

        // Simulate network delay / "thinking"
        setTimeout(() => {
            let text = "";
            const riskCount = identifiedRisks.length;
            const annualWaste = (frictionCost * 12).toLocaleString();

            if (type === 'linkedin') {
                text = `🚨 The "Swivel Chair" Tax is killing your margins.\n\n` +
                    `We just audited the tech stack at ${companyName || 'a client'}, and the numbers are brutal.\n\n` +
                    `• ${riskCount} "Shadow AI" tools found(unmanaged).\n` +
                    `• $${frictionCost.toLocaleString()}/mo in estimated friction costs.\n` +
                    `• ${shieldScore < 80 ? 'CRITICAL' : 'Moderate'} governance gaps detected.\n\n` +
                    `Most CEOs think AI is a "productivity unlock." In reality, without orchestration, it's just efficient chaos. ` +
                    `We found that ${costBasis.employeeCount} employees are wasting ~${costBasis.remediationTimePerIncident}h/week just fixing data errors between these tools.\n\n` +
                    `Don't just deploy agents. Orchestrate them.\n\n` +
                    `#AIOps #SovereignArchitect #EnterpriseAI #DigitalTransformation`;
            }
            else if (type === 'blog') {
                text = `# The State of AI at ${companyName}: A Wake-Up Call\n\n` +
                    `**Executive Summary**\n` +
                    `While the market hypes "Generative AI," our internal audit reveals a different reality: fragmentated tool adoption is creating a technical debt liability of $${annualWaste} annually.\n\n` +
                    `## The "Shadow" Reality\n` +
                    `Our Phase 1 analysis detected ${riskCount} unauthorized AI tools currently processing company data. This isn't just a security risk (Score: ${shieldScore}/100); it's an operational leak.\n\n` +
                    `## The Path Forward\n` +
                    `We are moving to Phase 2: Remediation. By deploying a sovereign orchestration layer, we aim to:\n` +
                    `1. Centralize governance.\n` +
                    `2. Reclaim lost productivity.\n` +
                    `3. Shift from "Ad-hoc usage" to "Strategic Deployment."\n\n` +
                    `*Generated by Maestro Architect*`;
            }
            else if (type === 'email') {
                text = `Subject: URGENT: Phase 1 Audit Results for ${companyName}\n\n` +
                    `Team,\n\n` +
                    `The results from our initial stack discovery are in, and we need to talk.\n\n` +
                    `We identified ${riskCount} critical risks that are currently exposing our PII. Using conservative estimates, this "efficiency drag" is costing us ~$${frictionCost.toLocaleString()} every month.\n\n` +
                    `I've attached the full Remediation Plan (Phase 2). We need to approve the "Governor" deployment by Friday to stop the bleeding.\n\n` +
                    `Let's discuss.\n\n` +
                    `Best,`;
            }

            setContent(text);
            setIsGenerating(false);
        }, 1500);
    };

    return (
        <div className="h-full flex flex-col bg-zinc-50 dark:bg-zinc-950 overflow-hidden">
            <header className="px-8 py-6 border-b border-border bg-card flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
                        <span className="text-primary">Phase 3:</span> Content Studio
                    </h1>
                    <p className="text-muted-foreground text-sm">Turn your Audit Insights into C-Suite Influence.</p>
                </div>
                <div className="flex items-center gap-2">
                    <span className="px-3 py-1 bg-secondary rounded-full text-xs font-mono text-muted-foreground">
                        Agent: <span className="text-primary font-bold">The Writer (PhD)</span>
                    </span>
                </div>
            </header>

            <div className="flex-1 flex overflow-hidden">
                {/* Left: Controls */}
                <div className="w-80 border-r border-border bg-card p-6 flex flex-col gap-6">
                    <div>
                        <label className="text-xs font-bold uppercase text-muted-foreground tracking-wider mb-4 block">Content Type</label>
                        <div className="space-y-2">
                            <button
                                onClick={() => setActiveTab('linkedin')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'linkedin' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <Linkedin className="w-4 h-4" />
                                <span className="text-sm font-medium">The Feed (LinkedIn)</span>
                            </button>
                            <button
                                onClick={() => setActiveTab('blog')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'blog' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <FileText className="w-4 h-4" />
                                <span className="text-sm font-medium">The Memo (Blog)</span>
                            </button>
                            <button
                                onClick={() => setActiveTab('email')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'email' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <Mic className="w-4 h-4" />
                                <span className="text-sm font-medium">The Update (Email)</span>
                            </button>
                        </div>
                    </div>

                    <div className="p-4 bg-muted/50 rounded-xl border border-border">
                        <h4 className="text-xs font-bold mb-2 flex items-center gap-2">
                            <Sparkles className="w-3 h-3 text-amber-500" />
                            Context Injected
                        </h4>
                        <ul className="text-[10px] space-y-1 text-muted-foreground">
                            <li className="flex justify-between"><span>Risks:</span> <span className="font-mono">{identifiedRisks.length}</span></li>
                            <li className="flex justify-between"><span>Cost:</span> <span className="font-mono">${frictionCost.toLocaleString()}</span></li>
                            <li className="flex justify-between"><span>Shield:</span> <span className="font-mono">{shieldScore}/100</span></li>
                        </ul>
                    </div>

                    <button
                        onClick={() => generateContent(activeTab)}
                        disabled={isGenerating}
                        className="mt-auto w-full py-3 bg-primary text-primary-foreground rounded-lg font-bold flex items-center justify-center gap-2 shadow-lg hover:bg-primary/90 transition-all active:scale-95 disabled:opacity-50"
                    >
                        {isGenerating ? (
                            <>
                                <RefreshCw className="w-4 h-4 animate-spin" /> Drafting...
                            </>
                        ) : (
                            <>
                                <PenTool className="w-4 h-4" /> Generate Draft
                            </>
                        )}
                    </button>
                </div>

                {/* Right: Preview */}
                <div className="flex-1 bg-zinc-100 dark:bg-zinc-900/50 p-8 overflow-y-auto flex justify-center">
                    <div className="max-w-2xl w-full bg-background border border-border rounded-xl shadow-sm min-h-[500px] flex flex-col relative">
                        <div className="p-4 border-b border-border flex justify-between items-center bg-muted/20 rounded-t-xl">
                            <span className="text-xs font-mono text-muted-foreground">preview.md</span>
                            <button
                                className="p-2 hover:bg-muted rounded text-muted-foreground transition-colors"
                                title="Copy to Clipboard"
                            >
                                <Copy className="w-4 h-4" />
                            </button>
                        </div>

                        <div className="p-8 flex-1 font-serif text-lg leading-relaxed whitespace-pre-wrap text-foreground/90">
                            {generatedContent ? (
                                generatedContent
                            ) : (
                                <div className="h-full flex flex-col items-center justify-center text-muted-foreground opacity-50">
                                    <PenTool className="w-12 h-12 mb-4 stroke-1" />
                                    <p>Select a format and generate content</p>
                                </div>
                            )}
                        </div>

                        {/* Tags / Persona Badge */}
                        <div className="p-4 border-t border-border bg-muted/10 rounded-b-xl flex gap-2">
                            <div className="text-[10px] px-2 py-0.5 bg-blue-500/10 text-blue-500 rounded border border-blue-500/20 font-medium">Tone: Authoritative</div>
                            <div className="text-[10px] px-2 py-0.5 bg-amber-500/10 text-amber-500 rounded border border-amber-500/20 font-medium">Reading Level: Grade 12</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

function SocialGenerator() {
    return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
                <div className="bg-card p-4 rounded-xl border border-border">
                    <label className="text-sm font-bold mb-2 block">Topic / Angle</label>
                    <textarea className="w-full h-32 bg-secondary/50 rounded-lg p-3 text-sm resize-none outline-none focus:ring-1 ring-primary" placeholder="e.g. Why 'Prompt Engineering' is a dead skill..." />
                </div>
                <div className="flex gap-2">
                    <button className="flex-1 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2">
                        LinkedIn Post
                    </button>
                    <button className="flex-1 py-2 bg-orange-600 hover:bg-orange-700 text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2">
                        Substack Article
                    </button>
                </div>
            </div>
            {/* Preview Area */}
            <div className="bg-card border border-border rounded-xl p-6 min-h-[300px] flex items-center justify-center text-muted-foreground border-dashed">
                <div className="text-center">
                    <Sparkles className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">AI Draft will appear here...</p>
                </div>
            </div>
        </div>
    )
}

function SpeechGenerator() {
    return (
        <div className="space-y-6">
            <div className="bg-card p-6 rounded-xl border border-border space-y-4">
                <h3 className="font-bold flex items-center gap-2"><Mic className="w-4 h-4" /> Keynote Parameters</h3>
                <div className="grid grid-cols-2 gap-4">
                    <select className="p-2 rounded-md bg-secondary text-sm"><option>Audience: C-Suite (Formal)</option><option>Audience: Tech Conf (Energy)</option></select>
                    <select className="p-2 rounded-md bg-secondary text-sm"><option>Duration: 15 min</option><option>Duration: 45 min</option></select>
                </div>
                <button className="w-full py-2 bg-primary text-primary-foreground rounded-lg">Generate Script</button>
            </div>
            <div className="bg-card border border-border rounded-xl p-6 h-[400px] overflow-auto font-mono text-sm leading-relaxed whitespace-pre-wrap">
                [WAITING FOR INPUT...]
            </div>
        </div>
    )
}

function HandoutGenerator() {
    return (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {["AI Opportunity Map", "Risk Mitigation Framework", "2026 Strategy One-Pager"].map(template => (
                <div key={template} className="bg-card hover:border-primary/50 transition-colors border border-border rounded-xl p-6 cursor-pointer group">
                    <div className="h-32 bg-secondary/50 rounded-lg mb-4 flex items-center justify-center">
                        <FileText className="w-8 h-8 text-muted-foreground group-hover:text-primary transition-colors" />
                    </div>
                    <h3 className="font-bold text-sm mb-1">{template}</h3>
                    <p className="text-xs text-muted-foreground mb-4">Standard Consultant Template</p>
                    <button className="w-full py-1.5 text-xs bg-primary/10 text-primary rounded-md font-bold flex items-center justify-center gap-1">
                        <Download className="w-3 h-3" /> Create PDF
                    </button>
                </div>
            ))}
        </div>
    )
}

function TabButton({ active, onClick, icon: Icon, label }: any) {
    return (
        <button
            onClick={onClick}
            className={`px-4 py-2 rounded-full text-sm font-medium flex items-center gap-2 transition-all ${active ? "bg-primary text-primary-foreground shadow-md" : "hover:bg-accent text-muted-foreground"
                }`}
        >
            <Icon className="w-4 h-4" />
            {label}
        </button>
    )
}
