import { useState } from 'react';
import { useClient } from '../../context/ClientContext';
import { PenTool, Linkedin, FileText, Mic, Copy, RefreshCw, Database, Download } from 'lucide-react';

type ContentType = 'linkedin' | 'blog' | 'email';

export function ContentStudio() {
    const { companyName, frictionCost, identifiedRisks, costBasis, shieldScore } = useClient();
    const [activeTab, setActiveTab] = useState<ContentType>('linkedin');
    const [generatedContent, setContent] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    // "Writer Agent" Logic (Simulated)
    const generateContent = (type: ContentType) => {
        setIsGenerating(true);
        setContent(''); // Clear previous

        // Simulate network delay / "thinking"
        setTimeout(() => {
            let text = "";
            const riskCount = identifiedRisks.length;
            const annualWaste = (frictionCost * 12).toLocaleString();

            if (type === 'linkedin') {
                text = `🚨 The "Swivel Chair" Tax is killing your margins.\n\n` +
                    `We just audited the tech stack at ${companyName || 'a client'}, and the numbers are brutal.\n\n` +
                    `• ${riskCount} "Shadow AI" tools found(unmanaged).\n` +
                    `• $${frictionCost.toLocaleString()}/mo in estimated friction costs.\n` +
                    `• ${shieldScore < 80 ? 'CRITICAL' : 'Moderate'} governance gaps detected.\n\n` +
                    `Most CEOs think AI is a "productivity unlock." In reality, without orchestration, it's just efficient chaos. ` +
                    `We found that ${costBasis.employeeCount} employees are wasting ~${costBasis.remediationTimePerIncident}h/week just fixing data errors between these tools.\n\n` +
                    `Don't just deploy agents. Orchestrate them.\n\n` +
                    `#AIOps #SovereignArchitect #EnterpriseAI #DigitalTransformation`;
            }
            else if (type === 'blog') {
                text = `# The State of AI at ${companyName}: A Wake-Up Call\n\n` +
                    `**Executive Summary**\n` +
                    `While the market hypes "Generative AI," our internal audit reveals a different reality: fragmentated tool adoption is creating a technical debt liability of $${annualWaste} annually.\n\n` +
                    `## The "Shadow" Reality\n` +
                    `Our Phase 1 analysis detected ${riskCount} unauthorized AI tools currently processing company data. This isn't just a security risk (Score: ${shieldScore}/100); it's an operational leak.\n\n` +
                    `## The Path Forward\n` +
                    `We are moving to Phase 2: Remediation. By deploying a sovereign orchestration layer, we aim to:\n` +
                    `1. Centralize governance.\n` +
                    `2. Reclaim lost productivity.\n` +
                    `3. Shift from "Ad-hoc usage" to "Strategic Deployment."\n\n` +
                    `*Generated by Maestro Architect*`;
            }
            else if (type === 'email') {
                text = `Subject: URGENT: Phase 1 Audit Results for ${companyName}\n\n` +
                    `Team,\n\n` +
                    `The results from our initial stack discovery are in, and we need to talk.\n\n` +
                    `We identified ${riskCount} critical risks that are currently exposing our PII. Using conservative estimates, this "efficiency drag" is costing us ~$${frictionCost.toLocaleString()} every month.\n\n` +
                    `I've attached the full Remediation Plan (Phase 2). We need to approve the "Governor" deployment by Friday to stop the bleeding.\n\n` +
                    `Let's discuss.\n\n` +
                    `Best,`;
            }

            setContent(text);
            setIsGenerating(false);
        }, 1500);
    };

    return (
        <div className="h-full flex flex-col bg-zinc-50 dark:bg-zinc-950 overflow-hidden">
            <header className="px-8 py-6 border-b border-zinc-800 bg-zinc-900/50 flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
                        <span className="text-purple-500 font-mono">Phase 3:</span>
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">Content Studio</span>
                    </h1>
                    <p className="text-zinc-400 text-sm mt-1">Turn your Audit Insights into C-Suite Influence.</p>
                </div>
                <div className="flex items-center gap-2">
                    <span className="px-3 py-1 bg-secondary rounded-full text-xs font-mono text-muted-foreground">
                        Agent: <span className="text-primary font-bold">The Writer (PhD)</span>
                    </span>
                </div>
            </header>

            <div className="flex-1 flex overflow-hidden">
                {/* Left: Controls */}
                <div className="w-80 border-r border-border bg-card p-6 flex flex-col gap-6">
                    <div>
                        <label className="text-xs font-bold uppercase text-muted-foreground tracking-wider mb-4 block">Content Type</label>
                        <div className="space-y-2">
                            <button
                                onClick={() => setActiveTab('linkedin')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'linkedin' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <Linkedin className="w-4 h-4" />
                                <span className="text-sm font-medium">The Feed (LinkedIn)</span>
                            </button>
                            <button
                                onClick={() => setActiveTab('blog')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'blog' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <FileText className="w-4 h-4" />
                                <span className="text-sm font-medium">The Memo (Blog)</span>
                            </button>
                            <button
                                onClick={() => setActiveTab('email')}
                                className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeTab === 'email' ? 'bg-primary/10 border-primary text-primary' : 'bg-background border-border hover:border-primary/50'}`}
                            >
                                <Mic className="w-4 h-4" />
                                <span className="text-sm font-medium">The Update (Email)</span>
                            </button>
                        </div>
                    </div>

                    <div className="bg-zinc-900/50 border border-zinc-800 rounded-lg p-4 mb-6">
                        <h3 className="text-xs font-bold uppercase text-zinc-500 mb-3 flex items-center gap-2">
                            <Database className="w-3 h-3" /> Context Injected
                        </h3>
                        <div className="space-y-2 text-xs">
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Governance Score:</span>
                                <span className="text-emerald-400 font-mono">{shieldScore}%</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Est. Friction Cost:</span>
                                <span className="text-red-400 font-mono">${frictionCost.toLocaleString()}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-zinc-400">Risk Factors:</span>
                                <span className="text-zinc-200">{identifiedRisks.length} incidents</span>
                            </div>
                        </div>
                    </div>
                    <button
                        onClick={() => generateContent(activeTab)}
                        disabled={isGenerating}
                        className="mt-auto w-full py-3 bg-primary text-primary-foreground rounded-lg font-bold flex items-center justify-center gap-2 shadow-lg hover:bg-primary/90 transition-all active:scale-95 disabled:opacity-50"
                    >
                        {isGenerating ? (
                            <>
                                <RefreshCw className="w-4 h-4 animate-spin" /> Drafting...
                            </>
                        ) : (
                            <>
                                <PenTool className="w-4 h-4" /> Generate Draft
                            </>
                        )}
                    </button>
                </div>

                {/* Right: Preview */}
                <div className="flex-1 bg-zinc-100 dark:bg-zinc-900/50 p-8 overflow-y-auto flex justify-center">
                    <div className="max-w-2xl w-full bg-background border border-border rounded-xl shadow-sm min-h-[500px] flex flex-col relative">
                        <div className="p-4 border-b border-border flex justify-between items-center bg-muted/20 rounded-t-xl">
                            <span className="text-xs font-mono text-muted-foreground">preview.md</span>
                            <div className="flex gap-2">
                                <button
                                    onClick={() => {
                                        navigator.clipboard.writeText(generatedContent);
                                        alert('Copied to clipboard!');
                                    }}
                                    disabled={!generatedContent}
                                    className="p-2 hover:bg-muted rounded text-muted-foreground transition-colors disabled:opacity-30"
                                    title="Copy to Clipboard"
                                >
                                    <Copy className="w-4 h-4" />
                                </button>
                                <button
                                    onClick={() => {
                                        const blob = new Blob([generatedContent], { type: 'text/plain' });
                                        const url = URL.createObjectURL(blob);
                                        const a = document.createElement('a');
                                        a.href = url;
                                        a.download = `${activeTab}-content.txt`;
                                        a.click();
                                        URL.revokeObjectURL(url);
                                    }}
                                    disabled={!generatedContent}
                                    className="p-2 hover:bg-muted rounded text-muted-foreground transition-colors disabled:opacity-30"
                                    title="Download as TXT"
                                >
                                    <Download className="w-4 h-4" />
                                </button>
                            </div>
                        </div>

                        <div className="p-8 flex-1 font-serif text-lg leading-relaxed whitespace-pre-wrap text-foreground/90">
                            {generatedContent ? (
                                generatedContent
                            ) : (
                                <div className="h-full flex flex-col items-center justify-center text-muted-foreground opacity-50">
                                    <PenTool className="w-12 h-12 mb-4 stroke-1" />
                                    <p>Select a format and generate content</p>
                                </div>
                            )}
                        </div>

                        {/* Tags / Persona Badge */}
                        <div className="p-4 border-t border-border bg-muted/10 rounded-b-xl flex gap-2">
                            <div className="text-[10px] px-2 py-0.5 bg-blue-500/10 text-blue-500 rounded border border-blue-500/20 font-medium">Tone: Authoritative</div>
                            <div className="text-[10px] px-2 py-0.5 bg-amber-500/10 text-amber-500 rounded border border-amber-500/20 font-medium">Reading Level: Grade 12</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

